In [9]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
from scipy.special import expit
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier


import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('importCleaned.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 20 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   imports  34 non-null     object 
 1   2000     34 non-null     float64
 2   2001     34 non-null     float64
 3   2002     34 non-null     float64
 4   2003     34 non-null     float64
 5   2004     34 non-null     float64
 6   2005     34 non-null     float64
 7   2006     34 non-null     float64
 8   2007     34 non-null     float64
 9   2008     34 non-null     float64
 10  2009     34 non-null     float64
 11  2010     34 non-null     float64
 12  2011     34 non-null     float64
 13  2012     34 non-null     float64
 14  2013     34 non-null     float64
 15  2014     34 non-null     float64
 16  2015     34 non-null     float64
 17  2016     34 non-null     float64
 18  2017     34 non-null     float64
 19  2018     34 non-null     float64
dtypes: float64(19), object(1)
memory usage: 5.4+ KB


In [10]:
df.describe()

2000          2001          2002          2003          2004  \
count     34.000000     34.000000     34.000000     34.000000     34.000000   
mean    2577.676471   2616.147059   2684.294118   2747.000000   2818.970588   
std     4694.852905   4452.344599   4562.339495   4716.287735   4898.082825   
min        9.000000      9.000000     10.000000     11.000000     16.000000   
25%      244.250000    279.500000    272.250000    292.500000    302.500000   
50%      810.000000    883.500000    892.500000    986.000000    959.500000   
75%     2868.500000   2991.250000   2918.250000   3132.500000   3193.500000   
max    23767.000000  21415.000000  21639.000000  22760.000000  23184.000000   

               2005          2006          2007          2008          2009  \
count     34.000000     34.000000     34.000000     34.000000     34.000000   
mean    2834.617647   2987.352941   3078.117647   3141.029412   3073.911765   
std     4826.150056   5105.277483   5258.548468   5329.922016   5200.654903   
min       16.000000     29.000000     16.000000     23.000000     14.000000   
25%      313.750000    338.750000    368.250000    393.750000    398.250000   
50%      962.000000    920.500000   1016.000000    968.500000    908.500000   
75%     3249.000000   3422.000000   3718.500000   3590.250000   3455.250000   
max    23042.000000  23709.000000  24219.000000  24277.000000  23578.000000   

               2010          2011          2012          2013          2014  \
count     34.000000     34.000000     34.000000     34.000000     34.000000   
mean    3210.205882   3288.617647   3328.617647   3409.647059   1288.676471   
std     5418.707823   5662.374724   5730.431789   5812.805800   4899.841127   
min       12.000000     17.000000     21.000000     22.000000      0.000000   
25%      380.500000    400.500000    397.750000    419.500000      0.000000   
50%     1012.500000   1005.000000   1101.500000   1123.500000      0.000000   
75%     3936.000000   3988.250000   3980.250000   4006.250000      0.000000   
max    24378.000000  26093.000000  26056.000000  27016.000000  27565.000000   

               2015          2016          2017          2018  
count     34.000000     34.000000     34.000000     34.000000  
mean    1308.470588   1358.176471   1378.055484   1356.119304  
std     4939.391075   5133.073829   5230.205856   5131.318623  
min        0.000000      0.000000      0.000000      0.000000  
25%        0.000000      0.000000      0.000000      0.000000  
50%        0.000000      0.000000      0.000000      0.000000  
75%        0.000000      0.000000      0.000000      0.000000  
max    27708.000000  28838.000000  29487.886464  28918.207055

In [11]:
#taking year 2000 mean

df['Index'] = 'Higher'
df.loc[df['2000']<= 2577,'Index'] ="Lower" 
X = df.iloc[0:34]#features
y = df['Index']#target
print(y)


0      Lower
1     Higher
2      Lower
3      Lower
4      Lower
5      Lower
6      Lower
7      Lower
8      Lower
9     Higher
10    Higher
11     Lower
12     Lower
13     Lower
14    Higher
15     Lower
16     Lower
17     Lower
18     Lower
19    Higher
20     Lower
21     Lower
22     Lower
23     Lower
24     Lower
25    Higher
26     Lower
27    Higher
28    Higher
29     Lower
30     Lower
31     Lower
32     Lower
33    Higher
Name: Index, dtype: object


In [12]:
X=pd.get_dummies(X)

In [13]:
X

2000     2001     2002     2003     2004     2005     2006     2007  \
0    1257.0   1432.0   1447.0   1336.0   1538.0   1577.0   1601.0   1968.0   
1    3491.0   3209.0   3792.0   3818.0   3968.0   4063.0   4605.0   4014.0   
2     281.0    355.0    343.0    400.0    367.0    441.0    435.0    393.0   
3     344.0    352.0    371.0    393.0    388.0    392.0    404.0    414.0   
4      69.0     59.0     57.0     59.0     59.0     80.0     74.0     71.0   
5     809.0    899.0    888.0    974.0    929.0   1063.0    940.0   1037.0   
6    1022.0   1103.0   1076.0   1002.0   1119.0    993.0   1004.0    995.0   
7     105.0    161.0    120.0    134.0    176.0    221.0    254.0    277.0   
8    1063.0   1084.0   1075.0   1105.0   1152.0   1156.0   1168.0   1207.0   
9    6520.0   6753.0   6925.0   6652.0   5940.0   5714.0   6191.0   6420.0   
10  13895.0  14753.0  15516.0  15727.0  17356.0  16716.0  18543.0  19564.0   
11    798.0    868.0    897.0    998.0    942.0    931.0    897.0   1081.0   
12    790.0    833.0    828.0    864.0    977.0    852.0    901.0    894.0   
13    155.0    180.0    177.0    227.0    264.0    251.0    252.0    266.0   
14   6315.0   6542.0   6523.0   6929.0   7032.0   7269.0   7548.0   8028.0   
15    181.0    156.0    164.0    186.0    188.0    191.0    221.0    151.0   
16    213.0    267.0    263.0    221.0    256.0    284.0    317.0    336.0   
17    232.0    210.0    253.0    289.0    316.0    331.0    336.0    360.0   
18      9.0      9.0     10.0     11.0     16.0     16.0     29.0     16.0   
19   2966.0   2794.0   2760.0   3176.0   3159.0   2988.0   3293.0   3531.0   
20   2576.0   2719.0   2643.0   2664.0   2687.0   2792.0   2654.0   2264.0   
21    811.0    843.0    838.0    834.0    838.0    831.0    862.0    911.0   
22    552.0    633.0    738.0    755.0    828.0    874.0    854.0    840.0   
23    286.0    317.0    300.0    303.0    298.0    308.0    347.0    508.0   
24    187.0    194.0    201.0    177.0    196.0    191.0    187.0    205.0   
25   3768.0   4058.0   4026.0   4136.0   4173.0   4356.0   4538.0   4875.0   
26   1344.0   1432.0   1463.0   1435.0   1495.0   1693.0   1820.0   1770.0   
27   3012.0   3062.0   2971.0   3002.0   3329.0   3433.0   4046.0   3781.0   
28   6908.0   6996.0   7307.0   6923.0   7254.0   7408.0   7632.0   7086.0   
29    662.0    716.0    698.0    691.0    716.0    753.0    731.0    780.0   
30   1890.0   3057.0   3504.0   3772.0   3205.0   3336.0   3465.0   4318.0   
31   1171.0   1255.0   1217.0   1322.0   1236.0   1641.0   1503.0   1823.0   
32    192.0    233.0    236.0    123.0    264.0    190.0    209.0    253.0   
33  23767.0  21415.0  21639.0  22760.0  23184.0  23042.0  23709.0  24219.0   

       2008     2009  ...  imports_   Sweden  imports_   United Kingdom  \
0    1901.0   1309.0  ...                  0                          0   
1    6792.0   5916.0  ...                  0                          0   
2     517.0    523.0  ...                  0                          0   
3     405.0    394.0  ...                  0                          0   
4      78.0     72.0  ...                  0                          0   
5    1037.0    930.0  ...                  0                          0   
6     900.0    860.0  ...                  0                          0   
7     334.0    357.0  ...                  0                          0   
8    1285.0   1243.0  ...                  0                          0   
9    6252.0   6670.0  ...                  0                          0   
10  19876.0  19416.0  ...                  0                          0   
11   1056.0   1046.0  ...                  0                          0   
12    811.0    704.0  ...                  0                          0   
13    127.0    142.0  ...                  0                          0   
14   8172.0   8078.0  ...                  0                          0   
15    154.0    132.0  ...                  0                          0   
1

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=40)

In [17]:
clf_gini = DecisionTreeClassifier(criterion = "gini",
  random_state = 100,max_depth=3, min_samples_leaf=5)

clf_gini.fit(X_train, y_train)

predictions_gini = clf_gini.predict(X_test)

clf_entropy = DecisionTreeClassifier(
            criterion = "entropy", random_state = 100,
            max_depth = 3, min_samples_leaf = 5)

clf_entropy.fit(X_train, y_train)
predictions_entropy = clf_entropy.predict(X_test)

In [18]:
def Report(y_test, y_pred):
    print("Report : ",
    classification_report(y_test, y_pred))

In [19]:
print("Trained acc clf gini: ", accuracy_score(y_train, clf_gini.predict(X_train)))
print("Test accuracy clf gini:", accuracy_score(y_test, predictions_gini))
print("Confusion matrix train gini: ", "\n", confusion_matrix(y_train, clf_gini.predict(X_train)))
print("Confusion matrix test gini: ", "\n",confusion_matrix(y_test, predictions_gini))

print("Trained acc clf entropy: ", accuracy_score(y_train, clf_entropy.predict(X_train)))
print("Test accuracy clf entropy:", accuracy_score(y_test, predictions_entropy))
print("Confusion matrix train entropy: ", "\n", confusion_matrix(y_train, clf_entropy.predict(X_train)))
print("Confusion matrix test entropy: ", "\n",confusion_matrix(y_test, predictions_entropy))

Trained acc clf gini:  1.0
Test accuracy clf gini: 0.9090909090909091
Confusion matrix train gini:  
 [[ 7  0]
 [ 0 16]]
Confusion matrix test gini:  
 [[2 0]
 [1 8]]
Trained acc clf entropy:  1.0
Test accuracy clf entropy: 0.9090909090909091
Confusion matrix train entropy:  
 [[ 7  0]
 [ 0 16]]
Confusion matrix test entropy:  
 [[2 0]
 [1 8]]


In [20]:
from sklearn.metrics import classification_report
print("GINI: Training")
print(Report(y_train, clf_gini.predict(X_train)))
print("GINI: Testing")
print(Report(y_test, predictions_gini))
print("---------------------------------------------------------")
print("ENTROPY: Training")
print(Report(y_train, clf_entropy.predict(X_train)))
print("ENTROPY: Testing")
print(Report(y_test, predictions_entropy))

GINI: Training
Report :                precision    recall  f1-score   support

      Higher       1.00      1.00      1.00         7
       Lower       1.00      1.00      1.00        16

    accuracy                           1.00        23
   macro avg       1.00      1.00      1.00        23
weighted avg       1.00      1.00      1.00        23

None
GINI: Testing
Report :                precision    recall  f1-score   support

      Higher       0.67      1.00      0.80         2
       Lower       1.00      0.89      0.94         9

    accuracy                           0.91        11
   macro avg       0.83      0.94      0.87        11
weighted avg       0.94      0.91      0.92        11

None
---------------------------------------------------------
ENTROPY: Training
Report :                precision    recall  f1-score   support

      Higher       1.00      1.00      1.00         7
       Lower       1.00      1.00      1.00        16

    accuracy                         