In [32]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score

import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('disCleaned.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   disappearance  34 non-null     object 
 1   2000           34 non-null     float64
 2   2001           34 non-null     float64
 3   2002           34 non-null     float64
 4   2003           34 non-null     float64
 5   2004           34 non-null     float64
 6   2005           34 non-null     float64
 7   2006           34 non-null     float64
 8   2007           34 non-null     float64
 9   2008           34 non-null     float64
 10  2009           34 non-null     float64
 11  2010           34 non-null     float64
 12  2011           34 non-null     float64
 13  2012           34 non-null     float64
 14  2013           34 non-null     float64
 15  2014           34 non-null     float64
 16  2015           34 non-null     float64
 17  2016           34 non-null     float64
 18  2017        

In [33]:
df.describe()

2000          2001          2002          2003          2004  \
count     34.000000     34.000000     34.000000     34.000000     34.000000   
mean    1978.263304   2055.005380   2065.774837   2132.612932   2194.215996   
std     3604.792965   3743.579295   3652.693403   3865.009684   4018.306377   
min        8.810502      9.084398      8.834243     10.562217     15.523023   
25%      209.635851    244.763782    244.453729    213.757411    268.026386   
50%      672.318176    727.717443    771.070696    721.805823    790.444509   
75%     1862.265526   2080.388437   2044.326119   2112.472338   2205.365742   
max    18745.563718  19553.653807  19124.510913  20192.677643  20972.762919   

               2005          2006          2007          2008          2009  \
count     34.000000     34.000000     34.000000     34.000000     34.000000   
mean    2153.509307   2194.003789   2219.055560   2212.674108   2167.366528   
std     3925.228589   3921.956362   3970.438805   4096.299707   4048.768126   
min       16.278455     28.811926     15.906515     22.747117     14.123640   
25%      243.463157    245.083907    279.130479    323.372708    238.612020   
50%      783.307871    795.253872    808.928780    730.532068    753.015118   
75%     2182.304922   2094.860177   2107.659513   1591.706320   1783.978934   
max    20997.544039  20667.379580  21033.273104  21652.427006  21435.967112   

               2010          2011          2012          2013          2014  \
count     34.000000     34.000000     34.000000     34.000000     34.000000   
mean    2233.255714   2229.554027   2242.030502   2305.882353   1102.911765   
std     4116.853588   4161.412146   4152.272249   4350.125186   4255.621960   
min       12.027799     15.557007     20.997838     22.000000      0.000000   
25%      310.372430    250.805028    223.632776    262.750000      0.000000   
50%      809.330489    830.412493    838.651628    865.500000      0.000000   
75%     1953.554586   1806.969227   1797.710208   1658.000000      0.000000   
max    21783.457919  22043.891384  22231.663715  23417.000000  23767.000000   

               2015          2016          2017          2018  
count     34.000000     34.000000     34.000000     34.000000  
mean    1127.088235   1172.558824   1195.823529   1206.431793  
std     4369.527264   4519.653568   4667.533632   4719.410405  
min        0.000000      0.000000      0.000000      0.000000  
25%        0.000000      0.000000      0.000000      0.000000  
50%        0.000000      0.000000      0.000000      0.000000  
75%        0.000000      0.000000      0.000000      0.000000  
max    24438.000000  25243.000000  26183.000000  26514.327404

In [34]:
df['Index'] = 'Higher'
df.loc[df['2000']<= 1978	,'Index'] ="Lower" 
X = df.iloc[0:34]#features
y = df['Index']#target
print(y)

0      Lower
1      Lower
2      Lower
3      Lower
4      Lower
5      Lower
6      Lower
7      Lower
8      Lower
9     Higher
10    Higher
11     Lower
12     Lower
13     Lower
14    Higher
15     Lower
16     Lower
17     Lower
18     Lower
19     Lower
20    Higher
21     Lower
22     Lower
23     Lower
24     Lower
25    Higher
26     Lower
27    Higher
28    Higher
29     Lower
30     Lower
31     Lower
32     Lower
33    Higher
Name: Index, dtype: object


In [35]:
X=pd.get_dummies(X)

In [36]:
X
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=40)

In [37]:
model = RandomForestClassifier(n_estimators = 34)
model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=34)

In [38]:
predict = model.predict(X_test)

In [39]:
def Report(y_test, y_pred):
    print("Report : ",
    classification_report(y_test, y_pred))

In [40]:
print("Trained acc: ", accuracy_score(y_train, model.predict(X_train)))
print("Test accuracy:", accuracy_score(y_test, predict))
print("Confusion matrix train: ", "\n", confusion_matrix(y_train, model.predict(X_train)))
print("Confusion matrix test: ", "\n",confusion_matrix(y_test, predict))

Trained acc:  1.0
Test accuracy: 0.9090909090909091
Confusion matrix train:  
 [[ 6  0]
 [ 0 17]]
Confusion matrix test:  
 [[2 0]
 [1 8]]


In [43]:
modelrf = RandomForestClassifier(max_depth=2,random_state=40)
modelrf.fit(X_train, y_train)
print('Training Accuracy : ',
      accuracy_score(y_train,modelrf.predict(X_train)))
print('Test Accuracy : ',
      accuracy_score(y_test,modelrf.predict(X_test)))
print("Confusion matrix train: ", "\n", confusion_matrix(y_train, model.predict(X_train)))
print("Confusion matrix test: ", "\n",confusion_matrix(y_test, predict))

Training Accuracy :  1.0
Test Accuracy :  0.9090909090909091
Confusion matrix train:  
 [[ 6  0]
 [ 0 17]]
Confusion matrix test:  
 [[2 0]
 [1 8]]


In [44]:
print(Report(y_train, model.predict(X_train)))
print("---------------------------------------------------------")
print(Report(y_test, predict))

Report :                precision    recall  f1-score   support

      Higher       1.00      1.00      1.00         6
       Lower       1.00      1.00      1.00        17

    accuracy                           1.00        23
   macro avg       1.00      1.00      1.00        23
weighted avg       1.00      1.00      1.00        23

None
---------------------------------------------------------
Report :                precision    recall  f1-score   support

      Higher       0.67      1.00      0.80         2
       Lower       1.00      0.89      0.94         9

    accuracy                           0.91        11
   macro avg       0.83      0.94      0.87        11
weighted avg       0.94      0.91      0.92        11

None
